import { LINE_NAMES } from './lines';

/* ------------------------------------------------------------------
   라인 분류는 라이엇 API에 없다.

   Data Dragon이 주는 건 tags(암살자/전사/마법사/원거리/서포터/탱커)뿐이고,
   CommunityDragon도 같은 분류만 준다. 라인은 챔피언의 고정 속성이 아니라
   패치마다 바뀌는 픽률 통계라서 정적 데이터로 존재하지 않는다.

   그래서 아래 표는 아래 메타 정보에 적힌 모델이 직접 분류한 것이다.
   공식 데이터도, 실제 픽률 집계도 아니다. 보조 필터로만 쓸 것.
   ------------------------------------------------------------------ */
export const LANE_META = {
  updatedAt: '2026-09-01',
  author: 'Claude Opus 5',
  patch: '16.17',
  note: '픽률 집계가 아니라 모델이 직접 분류한 참고 데이터입니다. 메타에 따라 실제와 다를 수 있어요.',
};

const T = '탑';
const J = '정글';
const M = '미드';
const A = '원딜';
const S = '서폿';

/* 값이 없는 챔피언은 '분류하지 않음'이다. 확신이 없으면 넣지 않는다.
   (16.17 기준 미분류: Zaahen, Locke) */
export const CHAMPION_LANES = {
  Aatrox: [T],
  Ahri: [M],
  Akali: [M, T],
  Akshan: [M, T],
  Alistar: [S],
  Ambessa: [T, M],
  Amumu: [J, S],
  Anivia: [M],
  Annie: [M, S],
  Aphelios: [A],
  Ashe: [A, S],
  AurelionSol: [M],
  Aurora: [M, T],
  Azir: [M],
  Bard: [S],
  Belveth: [J],
  Blitzcrank: [S],
  Brand: [S, M],
  Braum: [S],
  Briar: [J],
  Caitlyn: [A],
  Camille: [T],
  Cassiopeia: [M],
  Chogath: [T],
  Corki: [M],
  Darius: [T],
  Diana: [J, M],
  DrMundo: [T, J],
  Draven: [A],
  Ekko: [J, M],
  Elise: [J],
  Evelynn: [J],
  Ezreal: [A],
  Fiddlesticks: [J, S],
  Fiora: [T],
  Fizz: [M],
  Galio: [M, S],
  Gangplank: [T],
  Garen: [T],
  Gnar: [T],
  Gragas: [J, T],
  Graves: [J],
  Gwen: [T, J],
  Hecarim: [J],
  Heimerdinger: [T, M, S],
  Hwei: [M, S],
  Illaoi: [T],
  Irelia: [T, M],
  Ivern: [J],
  Janna: [S],
  JarvanIV: [J],
  Jax: [T, J],
  Jayce: [T, M],
  Jhin: [A],
  Jinx: [A],
  KSante: [T],
  Kaisa: [A],
  Kalista: [A],
  Karma: [S, M],
  Karthus: [J, M],
  Kassadin: [M],
  Katarina: [M],
  Kayle: [T, M],
  Kayn: [J],
  Kennen: [T],
  Khazix: [J],
  Kindred: [J],
  Kled: [T],
  KogMaw: [A],
  Leblanc: [M],
  LeeSin: [J],
  Leona: [S],
  Lillia: [J],
  Lissandra: [M],
  Lucian: [A, M],
  Lulu: [S],
  Lux: [M, S],
  Malphite: [T, S],
  Malzahar: [M],
  Maokai: [S, J, T],
  MasterYi: [J],
  Mel: [M, S],
  Milio: [S],
  MissFortune: [A],
  MonkeyKing: [T, J],
  Mordekaiser: [T],
  Morgana: [S, M],
  Naafiri: [M, J],
  Nami: [S],
  Nasus: [T],
  Nautilus: [S],
  Neeko: [M, S],
  Nidalee: [J],
  Nilah: [A],
  Nocturne: [J],
  Nunu: [J],
  Olaf: [T, J],
  Orianna: [M],
  Ornn: [T],
  Pantheon: [T, S, M],
  Poppy: [J, T, S],
  Pyke: [S],
  Qiyana: [M],
  Quinn: [T],
  Rakan: [S],
  Rammus: [J],
  RekSai: [J],
  Rell: [S],
  Renata: [S],
  Renekton: [T],
  Rengar: [J, T],
  Riven: [T],
  Rumble: [T, J],
  Ryze: [M, T],
  Samira: [A],
  Sejuani: [J],
  Senna: [S, A],
  Seraphine: [S, M],
  Sett: [T, S],
  Shaco: [J, S],
  Shen: [T],
  Shyvana: [J],
  Singed: [T],
  Sion: [T],
  Sivir: [A],
  Skarner: [J],
  Smolder: [A],
  Sona: [S],
  Soraka: [S],
  Swain: [M, S, T],
  Sylas: [M, T],
  Syndra: [M],
  TahmKench: [S, T],
  Taliyah: [M, J],
  Talon: [M, J],
  Taric: [S],
  Teemo: [T],
  Thresh: [S],
  Tristana: [A, M],
  Trundle: [J, T],
  Tryndamere: [T],
  TwistedFate: [M],
  Twitch: [A],
  Udyr: [J],
  Urgot: [T],
  Varus: [A],
  Vayne: [A, T],
  Veigar: [M],
  Velkoz: [M, S],
  Vex: [M],
  Vi: [J],
  Viego: [J],
  Viktor: [M],
  Vladimir: [M, T],
  Volibear: [T, J],
  Warwick: [J, T],
  Xayah: [A],
  Xerath: [M, S],
  XinZhao: [J],
  Yasuo: [M, T],
  Yone: [M, T],
  Yorick: [T],
  Yunara: [A],
  Yuumi: [S],
  Zac: [J],
  Zed: [M],
  Zeri: [A],
  Ziggs: [M, A],
  Zilean: [S, M],
  Zoe: [M],
  Zyra: [S],
};

export const lanesOf = (championId) => CHAMPION_LANES[championId] || [];

/* 표에 없는 챔피언 수. 새 챔피언이 출시되면 자동으로 늘어난다 */
export const countUnclassified = (champions) =>
  champions.filter((c) => !CHAMPION_LANES[c.id]).length;

export { LINE_NAMES };
